#!/bin/sh
set -e

export RED='\033[1;31m'
export BLUE='\033[1;34m'
export NOCOLOR='\033[0m'

if ! git diff --cached --quiet requirements.in
then
  if git diff --cached --quiet requirements.txt
  then
    echo $BLUE"┏━┅┉\n┋ Changes to requirements.in but not requirements.txt! Recompiling...\n┗━┅┉"$NOCOLOR
    make requirements
    echo $BLUE"┏━┅┉\n┋ Adding requirements.txt to commit...\n┗━┅┉"$NOCOLOR
    git add requirements.txt
  fi
else
  if ! git diff --cached  --quiet requirements.txt
  then
    echo $RED"┏━┅┉\n┋ Changes to requirements.txt but not requirements.in!"
    echo "┋ Move your changes to requirements.in, then run 'make requirements'.\n┗━┅┉"$NOCOLOR
    exit 1
  fi
fi

changes=$(git diff --cached --name-only)
make test
git add "$(echo "$changes" | paste -s -d " " -)"
