[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[tool.isort]
multi_line_output = 3  # compatible with black
